server:
  port: 8081
spring:
  application:
    name: iteam-service
  datasource:
    url: jdbc:mysql:///ssm
    data-username: root
    data-password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
mybatis:
  type-aliases-package: com.leyou.item.pojo